platform :ios, '9.0'

target 'Cobalt_Creek_Highschool_Library' do
  use_frameworks!

pod 'Firebase/Database'
pod 'Firebase/Core'
pod 'Firebase/Storage'
pod 'Firebase/Auth'
pod 'Firebase/Messaging'
pod 'OAuthSwift','~> 1.1.2'

  # Pods for Cobalt_Creek_Highschool_Library

end
